services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 8080

  # Init container to set up permissions
  permissions:
    image: alpine:latest
    user: "0:0"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/logs:/logs
    command: >
      sh -c "
        echo 'Setting up directory permissions for UID 1000...' &&
        mkdir -p /data /logs &&
        chown -R 1000:1000 /data /logs &&
        chmod -R 755 /data /logs &&
        echo 'Permissions set successfully!'
      "
    restart: "no"

  web:
    image: ghcr.io/switch-900/bitmap-brc-420-indexer:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    depends_on:
      - permissions
    volumes:
      - ${APP_DATA_DIR}/data:/app/db
      - ${APP_DATA_DIR}/logs:/app/logs
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_PATH: /app/db/brc420.db      # Enable indexer auto-start
      RUN_INDEXER: "true"
      # Official Umbrel environment variables (from framework docs)
      BITCOIN_RPC_HOST: ${APP_BITCOIN_NODE_IP:-umbrel.local}
      BITCOIN_RPC_PORT: ${APP_BITCOIN_RPC_PORT:-8332}
      BITCOIN_RPC_USER: ${APP_BITCOIN_RPC_USER:-umbrel}
      BITCOIN_RPC_PASS: ${APP_BITCOIN_RPC_PASS:-moneyprintergobrrr}
      # Ordinals service discovery (optional - will auto-detect)
      APP_ORDINALS_NODE_IP: ${APP_ORDINALS_NODE_IP}
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-umbrel}
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME:-umbrel.local}
      # External APIs as fallback (FIXED - no /api suffix for ordinals.com)
      API_URL: https://ordinals.com
      API_WALLET_URL: https://mempool.space/api
      START_BLOCK: 792435
      RETRY_BLOCK_DELAY: 3
      MAX_RETRIES: 3
      RETRY_DELAY: 5000
      CONCURRENCY_LIMIT: 5
    command: ["node", "server.js"]

networks:
  default:
    external: true
    name: umbrel_main_network
