version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitcoin-indexers-brc420_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/switch-900/brc-420-indexer:latest
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/db
      - ${APP_DATA_DIR}/logs:/app/logs
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_PATH: /app/db/brc420.db
      # Connect to local Umbrel services
      ORD_API_URL: http://${APP_ORDINALS_NODE_IP}:4000/api
      BITCOIN_RPC_HOST: ${APP_BITCOIN_NODE_IP}
      BITCOIN_RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      BITCOIN_RPC_USER: ${APP_BITCOIN_RPC_USER}
      BITCOIN_RPC_PASS: ${APP_BITCOIN_RPC_PASS}
      # Fallback to external APIs if needed
      API_URL: https://ordinals.com/api
      API_WALLET_URL: https://mempool.space/api
      START_BLOCK: 792435
      RETRY_BLOCK_DELAY: 3
      MAX_RETRIES: 3
      RETRY_DELAY: 5000
      CONCURRENCY_LIMIT: 5
      RUN_INDEXER: true
    command: ["node", "server.js"]
