services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 8080
    depends_on:
      web:
        condition: service_healthy

  # Init container to set up permissions
  permissions:
    image: alpine:latest
    user: "0:0"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/logs:/logs
    command: >
      sh -c "
        echo 'Setting up directory permissions for UID 1000...' &&
        mkdir -p /data /logs &&
        chown -R 1000:1000 /data /logs &&
        chmod -R 755 /data /logs &&
        echo 'Permissions set successfully!'
      "
    restart: "no"

  web:
    image: ghcr.io/switch-900/bitmap-brc-420-indexer:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    depends_on:
      - permissions
    volumes:
      - ${APP_DATA_DIR}/data:/app/db
      - ${APP_DATA_DIR}/logs:/app/logs
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_PATH: /app/db/brc420.db
      # Enable indexer auto-start
      RUN_INDEXER: "true"
      # HTTP API only configuration for Umbrel (no Bitcoin RPC)
      USE_LOCAL_APIS_ONLY: "true"
      # Umbrel service discovery - these will be automatically detected
      ORD_API_URL: http://ordinals_web_1:4000
      API_WALLET_URL: http://mempool_web_1:3006/api
      # Umbrel device info
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-umbrel}
      DEVICE_DOMAIN_NAME: ${DEVICE_DOMAIN_NAME:-umbrel.local}
      # Ordinals service discovery (optional - will auto-detect)
      APP_ORDINALS_NODE_IP: ${APP_ORDINALS_NODE_IP}
      APP_MEMPOOL_NODE_IP: ${APP_MEMPOOL_NODE_IP}
      APP_MEMPOOL_API_IP: ${APP_MEMPOOL_API_IP}
      # External APIs as fallback (only used if local unavailable)
      API_URL: https://ordinals.com
      # Indexing configuration
      START_BLOCK: 792435
      RETRY_BLOCK_DELAY: 3
      MAX_RETRIES: 3
      RETRY_DELAY: 5000
      CONCURRENCY_LIMIT: 5
    command: ["node", "server.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health", "||", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    external: true
    name: umbrel_main_network
